import type { EntityType } from '../enums/entity-type.enum.js';
import type { FileStatus } from '../enums/file-status.enum.js';
import type { RejectionReason } from '../enums/rejection-reason.enum.js';
import type { ValidationMode } from '../enums/validation-mode.enum.js';

export interface CreatePendingFileInput {
  /** Generated by the application (`FileId.generate()`). */
  id: string;
  ownerId: string;
  entityType: EntityType;
  declaredMimeType: string;
  declaredSize: number;
  quarantineKey: string;
  validationMode: ValidationMode;
  uploadExpiresAt: Date;
}

export interface ConfirmUploadInput {
  fileId: string;
  ownerId: string;
  actualSize: number;
}

export interface ConfirmUploadResult {
  id: string;
  validationMode: ValidationMode;
}

export interface CompleteScanInput {
  fileId: string;
  publicKey: string;
}

export interface RejectScanInput {
  fileId: string;
  reason: RejectionReason;
}

/** Outcome of an applied `completeScan` / `rejectScan` transition. */
export interface ScanTransitionResult {
  fileId: string;
  /** Attachment status read in the `RETURNING` of the transition itself. */
  status: FileStatus;
  /** True when `storage.file_scanned` / `storage.file_rejected` was written to `event_queue`. */
  eventEmitted: boolean;
}

/** Raw `files` columns returned by the `UPDATE ... RETURNING` of the scan transitions. */
export interface ScanTransitionRow {
  id: string;
  status: FileStatus;
  entity_type: EntityType;
  entity_id: string | null;
  owner_id: string;
}
