// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.13.0
//   protoc               unknown
// source: volontariapp/storage/storage.proto

/* eslint-disable */
import { Timestamp } from "../google/protobuf/timestamp.js";

export enum FileStatus {
  FILE_STATUS_UNSPECIFIED = 0,
  FILE_STATUS_PENDING = 1,
  FILE_STATUS_ATTACHED = 2,
  FILE_STATUS_ORPHANED = 3,
  FILE_STATUS_DELETED = 4,
  FILE_STATUS_RESERVED = 5,
  UNRECOGNIZED = -1,
}

export enum ScanStatus {
  SCAN_STATUS_UNSPECIFIED = 0,
  SCAN_STATUS_AWAITING_UPLOAD = 1,
  SCAN_STATUS_SCANNING = 2,
  SCAN_STATUS_CLEAN = 3,
  SCAN_STATUS_REJECTED = 4,
  UNRECOGNIZED = -1,
}

export enum ValidationMode {
  VALIDATION_MODE_UNSPECIFIED = 0,
  VALIDATION_MODE_SYNC = 1,
  VALIDATION_MODE_ASYNC = 2,
  UNRECOGNIZED = -1,
}

export enum RejectionReason {
  REJECTION_REASON_UNSPECIFIED = 0,
  REJECTION_REASON_SIZE_MISMATCH = 1,
  REJECTION_REASON_MIME_MISMATCH = 2,
  REJECTION_REASON_MALWARE = 3,
  REJECTION_REASON_UNDECODABLE = 4,
  REJECTION_REASON_SCAN_TIMEOUT = 5,
  UNRECOGNIZED = -1,
}

export enum EntityType {
  ENTITY_TYPE_UNSPECIFIED = 0,
  ENTITY_TYPE_POST = 1,
  ENTITY_TYPE_USER_AVATAR = 2,
  ENTITY_TYPE_BADGE_ICON = 3,
  ENTITY_TYPE_EVENT_COVER = 4,
  UNRECOGNIZED = -1,
}

export interface FileMetadata {
  id: string;
  ownerId: string;
  /**
   * Public object key when scan_status is CLEAN, empty otherwise.
   * The quarantine key is never exposed.
   */
  objectKey: string;
  mimeType: string;
  status: FileStatus;
  entityType?: EntityType | undefined;
  entityId?:
    | string
    | undefined;
  /**
   * Deprecated: visibility is derived from scan_status.
   *
   * @deprecated
   */
  isPublic: boolean;
  uploadExpiresAt: Timestamp | undefined;
  createdAt: Timestamp | undefined;
  updatedAt: Timestamp | undefined;
  scanStatus: ScanStatus;
  rejectionReason?:
    | RejectionReason
    | undefined;
  /** Set only when scan_status is CLEAN. */
  publicUrl?:
    | string
    | undefined;
  /** SYNC or ASYNC, after a possible switch. */
  validationMode: ValidationMode;
}
