// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: volontariapp/storage/storage.proto

/* eslint-disable */
import { Timestamp } from "../google/protobuf/timestamp.js";

export enum FileStatus {
  FILE_STATUS_UNSPECIFIED = 0,
  FILE_STATUS_PENDING = 1,
  FILE_STATUS_ATTACHED = 2,
  FILE_STATUS_ORPHANED = 3,
  FILE_STATUS_DELETED = 4,
  UNRECOGNIZED = -1,
}

export enum EntityType {
  ENTITY_TYPE_UNSPECIFIED = 0,
  ENTITY_TYPE_POST = 1,
  ENTITY_TYPE_USER_AVATAR = 2,
  ENTITY_TYPE_BADGE_ICON = 3,
  ENTITY_TYPE_EVENT_COVER = 4,
  UNRECOGNIZED = -1,
}

export interface FileMetadata {
  id: string;
  ownerId: string;
  objectKey: string;
  mimeType: string;
  status: FileStatus;
  entityType?: EntityType | undefined;
  entityId?: string | undefined;
  isPublic: boolean;
  uploadExpiresAt: Timestamp | undefined;
  createdAt: Timestamp | undefined;
  updatedAt: Timestamp | undefined;
}
