// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: volontariapp/common/geo.proto

/* eslint-disable */

export interface Point {
  latitude: number;
  longitude: number;
}

export interface GeoCircle {
  center: Point | undefined;
  radiusMeters: number;
}
