// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/social/social.command.proto

export interface CreateSocialUserCommand {
  userId: string;
}

export interface DeleteSocialUserCommand {
  userId: string;
}

export interface PostFollowUserCommand {
  followerId: string;
  followedId: string;
}

export interface DeleteFollowUserCommand {
  followerId: string;
  followedId: string;
}

export interface PostBlockUserCommand {
  blockerId: string;
  blockedId: string;
}

export interface DeleteBlockUserCommand {
  blockerId: string;
  blockedId: string;
}

export interface CreateSocialPostCommand {
  postId: string;
}

export interface DeleteSocialPostCommand {
  postId: string;
}

export interface PostUserOwnCommand {
  userId: string;
  postId: string;
}

export interface DeleteUserOwnCommand {
  userId: string;
  postId: string;
}

export interface PostLikePostCommand {
  userId: string;
  postId: string;
}

export interface DeleteLikePostCommand {
  userId: string;
  postId: string;
}

export interface CreateSocialEventCommand {
  eventId: string;
}

export interface DeleteSocialEventCommand {
  eventId: string;
}

export interface PostUserEventCommand {
  userId: string;
  eventId: string;
}

export interface DeleteUserEventCommand {
  userId: string;
  eventId: string;
}

export interface PostUserParticipateEventCommand {
  userId: string;
  eventId: string;
}

export interface DeleteUserParticipateEventCommand {
  userId: string;
  eventId: string;
}

export interface LinkPostToEventCommand {
  postId: string;
  eventId: string;
}

export interface UnlinkPostFromEventCommand {
  postId: string;
  eventId: string;
}
