// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/social/social.query.proto

/* eslint-disable */
import { PaginationRequest } from "../common/pagination.js";

export interface GetSocialUserQuery {
  userId: string;
}

export interface GetMyFollowsQuery {
  userId: string;
  pagination: PaginationRequest | undefined;
}

export interface GetMyFollowersQuery {
  userId: string;
  pagination: PaginationRequest | undefined;
}

export interface GetMyBlocksQuery {
  userId: string;
  pagination: PaginationRequest | undefined;
}

export interface GetWhoBlockedMeQuery {
  userId: string;
  pagination: PaginationRequest | undefined;
}

export interface GetSocialPostQuery {
  postId: string;
}

export interface GetUserPostsQuery {
  userId: string;
  pagination: PaginationRequest | undefined;
}

export interface GetFeedQuery {
  userId: string;
  pagination: PaginationRequest | undefined;
}

export interface GetUserLikesQuery {
  userId: string;
  pagination: PaginationRequest | undefined;
}

export interface GetPostLikersQuery {
  postId: string;
  pagination: PaginationRequest | undefined;
}

export interface GetUserEventQuery {
  userId: string;
  pagination: PaginationRequest | undefined;
}

export interface GetUserParticipateEventQuery {
  userId: string;
  pagination: PaginationRequest | undefined;
}

export interface GetEventParticipantsQuery {
  eventId: string;
  pagination: PaginationRequest | undefined;
}

export interface GetEventRelatedToPostQuery {
  postId: string;
}

export interface GetEventPostsQuery {
  eventId: string;
  pagination: PaginationRequest | undefined;
}
