// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: volontariapp/social/social.services.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import {
  AdminDeleteBlockUserCommand,
  AdminDeleteFollowUserCommand,
  AdminDeleteLikePostCommand,
  AdminDeleteUserOwnCommand,
  AdminDeleteUserParticipateEventCommand,
  AdminDeleteUserWishEventCommand,
  AdminPostBlockUserCommand,
  AdminPostFollowUserCommand,
  AdminPostLikePostCommand,
  AdminPostUserOwnCommand,
  AdminPostUserParticipateEventCommand,
  AdminPostUserWishEventCommand,
  CreateSocialEventCommand,
  CreateSocialPostCommand,
  CreateSocialUserCommand,
  DeleteBlockUserCommand,
  DeleteFollowUserCommand,
  DeleteLikePostCommand,
  DeleteSocialEventCommand,
  DeleteSocialPostCommand,
  DeleteSocialUserCommand,
  DeleteUserEventCommand,
  DeleteUserOwnCommand,
  DeleteUserParticipateEventCommand,
  DeleteUserWishEventCommand,
  LinkPostToEventCommand,
  PostBlockUserCommand,
  PostFollowUserCommand,
  PostLikePostCommand,
  PostUserEventCommand,
  PostUserOwnCommand,
  PostUserParticipateEventCommand,
  PostUserWishEventCommand,
  UnlinkPostFromEventCommand,
} from "./social.command.js";
import {
  AdminGetFeedQuery,
  AdminGetMyBlocksQuery,
  AdminGetMyFollowersQuery,
  AdminGetMyFollowsQuery,
  AdminGetUserEventQuery,
  AdminGetUserLikesQuery,
  AdminGetUserParticipateEventQuery,
  AdminGetUserPostsQuery,
  AdminGetUserWishEventQuery,
  AdminGetWhoBlockedMeQuery,
  GetEventParticipantsQuery,
  GetEventPostsQuery,
  GetEventRelatedToPostQuery,
  GetEventsRelatedToPostsQuery,
  GetFeedQuery,
  GetMyBlocksQuery,
  GetMyFollowersQuery,
  GetMyFollowsQuery,
  GetPostLikersQuery,
  GetSocialEventQuery,
  GetSocialPostQuery,
  GetSocialUserQuery,
  GetUserEventQuery,
  GetUserLikesQuery,
  GetUserParticipateEventQuery,
  GetUserPostsQuery,
  GetUserWishEventQuery,
  GetWhoBlockedMeQuery,
} from "./social.query.js";
import {
  AdminDeleteBlockUserResponse,
  AdminDeleteFollowUserResponse,
  AdminDeleteLikePostResponse,
  AdminDeleteUserOwnResponse,
  AdminDeleteUserParticipateEventResponse,
  AdminDeleteUserWishEventResponse,
  AdminGetFeedResponse,
  AdminGetMyBlocksResponse,
  AdminGetMyFollowersResponse,
  AdminGetMyFollowsResponse,
  AdminGetUserEventResponse,
  AdminGetUserLikesResponse,
  AdminGetUserParticipateEventResponse,
  AdminGetUserPostsResponse,
  AdminGetUserWishEventResponse,
  AdminGetWhoBlockedMeResponse,
  AdminPostBlockUserResponse,
  AdminPostFollowUserResponse,
  AdminPostLikePostResponse,
  AdminPostUserOwnResponse,
  AdminPostUserParticipateEventResponse,
  AdminPostUserWishEventResponse,
  CreateEventNodeResponse,
  CreatePostNodeResponse,
  CreateUserNodeResponse,
  DeleteBlockUserResponse,
  DeleteEventNodeResponse,
  DeleteFollowUserResponse,
  DeleteLikePostResponse,
  DeletePostNodeResponse,
  DeleteUserEventResponse,
  DeleteUserNodeResponse,
  DeleteUserOwnResponse,
  DeleteUserParticipateEventResponse,
  DeleteUserWishEventResponse,
  GetEventNodeResponse,
  GetEventParticipantsResponse,
  GetEventPostsResponse,
  GetEventRelatedToPostResponse,
  GetEventsRelatedToPostsResponse,
  GetFeedResponse,
  GetMyBlocksResponse,
  GetMyFollowersResponse,
  GetMyFollowsResponse,
  GetPostLikersResponse,
  GetPostNodeResponse,
  GetUserEventResponse,
  GetUserLikesResponse,
  GetUserNodeResponse,
  GetUserParticipateEventResponse,
  GetUserPostsResponse,
  GetUserWishEventResponse,
  GetWhoBlockedMeResponse,
  LinkPostToEventResponse,
  PostBlockUserResponse,
  PostFollowUserResponse,
  PostLikePostResponse,
  PostUserEventResponse,
  PostUserOwnResponse,
  PostUserParticipateEventResponse,
  PostUserWishEventResponse,
  UnlinkPostFromEventResponse,
} from "./social.responses.js";

export interface SocialUserNodeCommandServiceClient {
  createUserNode(request: CreateSocialUserCommand): Observable<CreateUserNodeResponse>;

  deleteUserNode(request: DeleteSocialUserCommand): Observable<DeleteUserNodeResponse>;
}

export interface SocialUserNodeCommandServiceController {
  createUserNode(
    request: CreateSocialUserCommand,
  ): Promise<CreateUserNodeResponse> | Observable<CreateUserNodeResponse> | CreateUserNodeResponse;

  deleteUserNode(
    request: DeleteSocialUserCommand,
  ): Promise<DeleteUserNodeResponse> | Observable<DeleteUserNodeResponse> | DeleteUserNodeResponse;
}

export function SocialUserNodeCommandServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createUserNode", "deleteUserNode"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SocialUserNodeCommandService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SocialUserNodeCommandService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SOCIAL_USER_NODE_COMMAND_SERVICE_NAME = "SocialUserNodeCommandService";

export interface SocialUserNodeQueryServiceClient {
  getUserNode(request: GetSocialUserQuery): Observable<GetUserNodeResponse>;
}

export interface SocialUserNodeQueryServiceController {
  getUserNode(
    request: GetSocialUserQuery,
  ): Promise<GetUserNodeResponse> | Observable<GetUserNodeResponse> | GetUserNodeResponse;
}

export function SocialUserNodeQueryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getUserNode"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SocialUserNodeQueryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SocialUserNodeQueryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SOCIAL_USER_NODE_QUERY_SERVICE_NAME = "SocialUserNodeQueryService";

export interface RelationshipCommandServiceClient {
  postFollowUser(request: PostFollowUserCommand): Observable<PostFollowUserResponse>;

  deleteFollowUser(request: DeleteFollowUserCommand): Observable<DeleteFollowUserResponse>;

  postBlockUser(request: PostBlockUserCommand): Observable<PostBlockUserResponse>;

  deleteBlockUser(request: DeleteBlockUserCommand): Observable<DeleteBlockUserResponse>;

  adminPostFollowUser(request: AdminPostFollowUserCommand): Observable<AdminPostFollowUserResponse>;

  adminDeleteFollowUser(request: AdminDeleteFollowUserCommand): Observable<AdminDeleteFollowUserResponse>;

  adminPostBlockUser(request: AdminPostBlockUserCommand): Observable<AdminPostBlockUserResponse>;

  adminDeleteBlockUser(request: AdminDeleteBlockUserCommand): Observable<AdminDeleteBlockUserResponse>;
}

export interface RelationshipCommandServiceController {
  postFollowUser(
    request: PostFollowUserCommand,
  ): Promise<PostFollowUserResponse> | Observable<PostFollowUserResponse> | PostFollowUserResponse;

  deleteFollowUser(
    request: DeleteFollowUserCommand,
  ): Promise<DeleteFollowUserResponse> | Observable<DeleteFollowUserResponse> | DeleteFollowUserResponse;

  postBlockUser(
    request: PostBlockUserCommand,
  ): Promise<PostBlockUserResponse> | Observable<PostBlockUserResponse> | PostBlockUserResponse;

  deleteBlockUser(
    request: DeleteBlockUserCommand,
  ): Promise<DeleteBlockUserResponse> | Observable<DeleteBlockUserResponse> | DeleteBlockUserResponse;

  adminPostFollowUser(
    request: AdminPostFollowUserCommand,
  ): Promise<AdminPostFollowUserResponse> | Observable<AdminPostFollowUserResponse> | AdminPostFollowUserResponse;

  adminDeleteFollowUser(
    request: AdminDeleteFollowUserCommand,
  ): Promise<AdminDeleteFollowUserResponse> | Observable<AdminDeleteFollowUserResponse> | AdminDeleteFollowUserResponse;

  adminPostBlockUser(
    request: AdminPostBlockUserCommand,
  ): Promise<AdminPostBlockUserResponse> | Observable<AdminPostBlockUserResponse> | AdminPostBlockUserResponse;

  adminDeleteBlockUser(
    request: AdminDeleteBlockUserCommand,
  ): Promise<AdminDeleteBlockUserResponse> | Observable<AdminDeleteBlockUserResponse> | AdminDeleteBlockUserResponse;
}

export function RelationshipCommandServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "postFollowUser",
      "deleteFollowUser",
      "postBlockUser",
      "deleteBlockUser",
      "adminPostFollowUser",
      "adminDeleteFollowUser",
      "adminPostBlockUser",
      "adminDeleteBlockUser",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("RelationshipCommandService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("RelationshipCommandService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const RELATIONSHIP_COMMAND_SERVICE_NAME = "RelationshipCommandService";

export interface RelationshipQueryServiceClient {
  getMyFollows(request: GetMyFollowsQuery): Observable<GetMyFollowsResponse>;

  getMyFollowers(request: GetMyFollowersQuery): Observable<GetMyFollowersResponse>;

  getMyBlocks(request: GetMyBlocksQuery): Observable<GetMyBlocksResponse>;

  getWhoBlockedMe(request: GetWhoBlockedMeQuery): Observable<GetWhoBlockedMeResponse>;

  adminGetMyFollows(request: AdminGetMyFollowsQuery): Observable<AdminGetMyFollowsResponse>;

  adminGetMyFollowers(request: AdminGetMyFollowersQuery): Observable<AdminGetMyFollowersResponse>;

  adminGetMyBlocks(request: AdminGetMyBlocksQuery): Observable<AdminGetMyBlocksResponse>;

  adminGetWhoBlockedMe(request: AdminGetWhoBlockedMeQuery): Observable<AdminGetWhoBlockedMeResponse>;
}

export interface RelationshipQueryServiceController {
  getMyFollows(
    request: GetMyFollowsQuery,
  ): Promise<GetMyFollowsResponse> | Observable<GetMyFollowsResponse> | GetMyFollowsResponse;

  getMyFollowers(
    request: GetMyFollowersQuery,
  ): Promise<GetMyFollowersResponse> | Observable<GetMyFollowersResponse> | GetMyFollowersResponse;

  getMyBlocks(
    request: GetMyBlocksQuery,
  ): Promise<GetMyBlocksResponse> | Observable<GetMyBlocksResponse> | GetMyBlocksResponse;

  getWhoBlockedMe(
    request: GetWhoBlockedMeQuery,
  ): Promise<GetWhoBlockedMeResponse> | Observable<GetWhoBlockedMeResponse> | GetWhoBlockedMeResponse;

  adminGetMyFollows(
    request: AdminGetMyFollowsQuery,
  ): Promise<AdminGetMyFollowsResponse> | Observable<AdminGetMyFollowsResponse> | AdminGetMyFollowsResponse;

  adminGetMyFollowers(
    request: AdminGetMyFollowersQuery,
  ): Promise<AdminGetMyFollowersResponse> | Observable<AdminGetMyFollowersResponse> | AdminGetMyFollowersResponse;

  adminGetMyBlocks(
    request: AdminGetMyBlocksQuery,
  ): Promise<AdminGetMyBlocksResponse> | Observable<AdminGetMyBlocksResponse> | AdminGetMyBlocksResponse;

  adminGetWhoBlockedMe(
    request: AdminGetWhoBlockedMeQuery,
  ): Promise<AdminGetWhoBlockedMeResponse> | Observable<AdminGetWhoBlockedMeResponse> | AdminGetWhoBlockedMeResponse;
}

export function RelationshipQueryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getMyFollows",
      "getMyFollowers",
      "getMyBlocks",
      "getWhoBlockedMe",
      "adminGetMyFollows",
      "adminGetMyFollowers",
      "adminGetMyBlocks",
      "adminGetWhoBlockedMe",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("RelationshipQueryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("RelationshipQueryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const RELATIONSHIP_QUERY_SERVICE_NAME = "RelationshipQueryService";

export interface PublicationCommandServiceClient {
  createPostNode(request: CreateSocialPostCommand): Observable<CreatePostNodeResponse>;

  deletePostNode(request: DeleteSocialPostCommand): Observable<DeletePostNodeResponse>;

  postUserOwn(request: PostUserOwnCommand): Observable<PostUserOwnResponse>;

  deleteUserOwn(request: DeleteUserOwnCommand): Observable<DeleteUserOwnResponse>;

  adminPostUserOwn(request: AdminPostUserOwnCommand): Observable<AdminPostUserOwnResponse>;

  adminDeleteUserOwn(request: AdminDeleteUserOwnCommand): Observable<AdminDeleteUserOwnResponse>;
}

export interface PublicationCommandServiceController {
  createPostNode(
    request: CreateSocialPostCommand,
  ): Promise<CreatePostNodeResponse> | Observable<CreatePostNodeResponse> | CreatePostNodeResponse;

  deletePostNode(
    request: DeleteSocialPostCommand,
  ): Promise<DeletePostNodeResponse> | Observable<DeletePostNodeResponse> | DeletePostNodeResponse;

  postUserOwn(
    request: PostUserOwnCommand,
  ): Promise<PostUserOwnResponse> | Observable<PostUserOwnResponse> | PostUserOwnResponse;

  deleteUserOwn(
    request: DeleteUserOwnCommand,
  ): Promise<DeleteUserOwnResponse> | Observable<DeleteUserOwnResponse> | DeleteUserOwnResponse;

  adminPostUserOwn(
    request: AdminPostUserOwnCommand,
  ): Promise<AdminPostUserOwnResponse> | Observable<AdminPostUserOwnResponse> | AdminPostUserOwnResponse;

  adminDeleteUserOwn(
    request: AdminDeleteUserOwnCommand,
  ): Promise<AdminDeleteUserOwnResponse> | Observable<AdminDeleteUserOwnResponse> | AdminDeleteUserOwnResponse;
}

export function PublicationCommandServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createPostNode",
      "deletePostNode",
      "postUserOwn",
      "deleteUserOwn",
      "adminPostUserOwn",
      "adminDeleteUserOwn",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PublicationCommandService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PublicationCommandService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PUBLICATION_COMMAND_SERVICE_NAME = "PublicationCommandService";

export interface PublicationQueryServiceClient {
  getPostNode(request: GetSocialPostQuery): Observable<GetPostNodeResponse>;

  getUserPosts(request: GetUserPostsQuery): Observable<GetUserPostsResponse>;

  getFeed(request: GetFeedQuery): Observable<GetFeedResponse>;

  adminGetUserPosts(request: AdminGetUserPostsQuery): Observable<AdminGetUserPostsResponse>;

  adminGetFeed(request: AdminGetFeedQuery): Observable<AdminGetFeedResponse>;
}

export interface PublicationQueryServiceController {
  getPostNode(
    request: GetSocialPostQuery,
  ): Promise<GetPostNodeResponse> | Observable<GetPostNodeResponse> | GetPostNodeResponse;

  getUserPosts(
    request: GetUserPostsQuery,
  ): Promise<GetUserPostsResponse> | Observable<GetUserPostsResponse> | GetUserPostsResponse;

  getFeed(request: GetFeedQuery): Promise<GetFeedResponse> | Observable<GetFeedResponse> | GetFeedResponse;

  adminGetUserPosts(
    request: AdminGetUserPostsQuery,
  ): Promise<AdminGetUserPostsResponse> | Observable<AdminGetUserPostsResponse> | AdminGetUserPostsResponse;

  adminGetFeed(
    request: AdminGetFeedQuery,
  ): Promise<AdminGetFeedResponse> | Observable<AdminGetFeedResponse> | AdminGetFeedResponse;
}

export function PublicationQueryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getPostNode", "getUserPosts", "getFeed", "adminGetUserPosts", "adminGetFeed"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PublicationQueryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PublicationQueryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PUBLICATION_QUERY_SERVICE_NAME = "PublicationQueryService";

export interface InteractionCommandServiceClient {
  postLikePost(request: PostLikePostCommand): Observable<PostLikePostResponse>;

  deleteLikePost(request: DeleteLikePostCommand): Observable<DeleteLikePostResponse>;

  adminPostLikePost(request: AdminPostLikePostCommand): Observable<AdminPostLikePostResponse>;

  adminDeleteLikePost(request: AdminDeleteLikePostCommand): Observable<AdminDeleteLikePostResponse>;
}

export interface InteractionCommandServiceController {
  postLikePost(
    request: PostLikePostCommand,
  ): Promise<PostLikePostResponse> | Observable<PostLikePostResponse> | PostLikePostResponse;

  deleteLikePost(
    request: DeleteLikePostCommand,
  ): Promise<DeleteLikePostResponse> | Observable<DeleteLikePostResponse> | DeleteLikePostResponse;

  adminPostLikePost(
    request: AdminPostLikePostCommand,
  ): Promise<AdminPostLikePostResponse> | Observable<AdminPostLikePostResponse> | AdminPostLikePostResponse;

  adminDeleteLikePost(
    request: AdminDeleteLikePostCommand,
  ): Promise<AdminDeleteLikePostResponse> | Observable<AdminDeleteLikePostResponse> | AdminDeleteLikePostResponse;
}

export function InteractionCommandServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["postLikePost", "deleteLikePost", "adminPostLikePost", "adminDeleteLikePost"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("InteractionCommandService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("InteractionCommandService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const INTERACTION_COMMAND_SERVICE_NAME = "InteractionCommandService";

export interface InteractionQueryServiceClient {
  getUserLikes(request: GetUserLikesQuery): Observable<GetUserLikesResponse>;

  getPostLikers(request: GetPostLikersQuery): Observable<GetPostLikersResponse>;

  adminGetUserLikes(request: AdminGetUserLikesQuery): Observable<AdminGetUserLikesResponse>;
}

export interface InteractionQueryServiceController {
  getUserLikes(
    request: GetUserLikesQuery,
  ): Promise<GetUserLikesResponse> | Observable<GetUserLikesResponse> | GetUserLikesResponse;

  getPostLikers(
    request: GetPostLikersQuery,
  ): Promise<GetPostLikersResponse> | Observable<GetPostLikersResponse> | GetPostLikersResponse;

  adminGetUserLikes(
    request: AdminGetUserLikesQuery,
  ): Promise<AdminGetUserLikesResponse> | Observable<AdminGetUserLikesResponse> | AdminGetUserLikesResponse;
}

export function InteractionQueryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getUserLikes", "getPostLikers", "adminGetUserLikes"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("InteractionQueryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("InteractionQueryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const INTERACTION_QUERY_SERVICE_NAME = "InteractionQueryService";

export interface ParticipationCommandServiceClient {
  createEventNode(request: CreateSocialEventCommand): Observable<CreateEventNodeResponse>;

  deleteEventNode(request: DeleteSocialEventCommand): Observable<DeleteEventNodeResponse>;

  postUserEvent(request: PostUserEventCommand): Observable<PostUserEventResponse>;

  deleteUserEvent(request: DeleteUserEventCommand): Observable<DeleteUserEventResponse>;

  postUserParticipateEvent(request: PostUserParticipateEventCommand): Observable<PostUserParticipateEventResponse>;

  deleteUserParticipateEvent(
    request: DeleteUserParticipateEventCommand,
  ): Observable<DeleteUserParticipateEventResponse>;

  postUserWishEvent(request: PostUserWishEventCommand): Observable<PostUserWishEventResponse>;

  deleteUserWishEvent(request: DeleteUserWishEventCommand): Observable<DeleteUserWishEventResponse>;

  adminPostUserParticipateEvent(
    request: AdminPostUserParticipateEventCommand,
  ): Observable<AdminPostUserParticipateEventResponse>;

  adminDeleteUserParticipateEvent(
    request: AdminDeleteUserParticipateEventCommand,
  ): Observable<AdminDeleteUserParticipateEventResponse>;

  adminPostUserWishEvent(request: AdminPostUserWishEventCommand): Observable<AdminPostUserWishEventResponse>;

  adminDeleteUserWishEvent(request: AdminDeleteUserWishEventCommand): Observable<AdminDeleteUserWishEventResponse>;
}

export interface ParticipationCommandServiceController {
  createEventNode(
    request: CreateSocialEventCommand,
  ): Promise<CreateEventNodeResponse> | Observable<CreateEventNodeResponse> | CreateEventNodeResponse;

  deleteEventNode(
    request: DeleteSocialEventCommand,
  ): Promise<DeleteEventNodeResponse> | Observable<DeleteEventNodeResponse> | DeleteEventNodeResponse;

  postUserEvent(
    request: PostUserEventCommand,
  ): Promise<PostUserEventResponse> | Observable<PostUserEventResponse> | PostUserEventResponse;

  deleteUserEvent(
    request: DeleteUserEventCommand,
  ): Promise<DeleteUserEventResponse> | Observable<DeleteUserEventResponse> | DeleteUserEventResponse;

  postUserParticipateEvent(
    request: PostUserParticipateEventCommand,
  ):
    | Promise<PostUserParticipateEventResponse>
    | Observable<PostUserParticipateEventResponse>
    | PostUserParticipateEventResponse;

  deleteUserParticipateEvent(
    request: DeleteUserParticipateEventCommand,
  ):
    | Promise<DeleteUserParticipateEventResponse>
    | Observable<DeleteUserParticipateEventResponse>
    | DeleteUserParticipateEventResponse;

  postUserWishEvent(
    request: PostUserWishEventCommand,
  ): Promise<PostUserWishEventResponse> | Observable<PostUserWishEventResponse> | PostUserWishEventResponse;

  deleteUserWishEvent(
    request: DeleteUserWishEventCommand,
  ): Promise<DeleteUserWishEventResponse> | Observable<DeleteUserWishEventResponse> | DeleteUserWishEventResponse;

  adminPostUserParticipateEvent(
    request: AdminPostUserParticipateEventCommand,
  ):
    | Promise<AdminPostUserParticipateEventResponse>
    | Observable<AdminPostUserParticipateEventResponse>
    | AdminPostUserParticipateEventResponse;

  adminDeleteUserParticipateEvent(
    request: AdminDeleteUserParticipateEventCommand,
  ):
    | Promise<AdminDeleteUserParticipateEventResponse>
    | Observable<AdminDeleteUserParticipateEventResponse>
    | AdminDeleteUserParticipateEventResponse;

  adminPostUserWishEvent(
    request: AdminPostUserWishEventCommand,
  ):
    | Promise<AdminPostUserWishEventResponse>
    | Observable<AdminPostUserWishEventResponse>
    | AdminPostUserWishEventResponse;

  adminDeleteUserWishEvent(
    request: AdminDeleteUserWishEventCommand,
  ):
    | Promise<AdminDeleteUserWishEventResponse>
    | Observable<AdminDeleteUserWishEventResponse>
    | AdminDeleteUserWishEventResponse;
}

export function ParticipationCommandServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createEventNode",
      "deleteEventNode",
      "postUserEvent",
      "deleteUserEvent",
      "postUserParticipateEvent",
      "deleteUserParticipateEvent",
      "postUserWishEvent",
      "deleteUserWishEvent",
      "adminPostUserParticipateEvent",
      "adminDeleteUserParticipateEvent",
      "adminPostUserWishEvent",
      "adminDeleteUserWishEvent",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ParticipationCommandService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ParticipationCommandService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PARTICIPATION_COMMAND_SERVICE_NAME = "ParticipationCommandService";

export interface ParticipationQueryServiceClient {
  getEventNode(request: GetSocialEventQuery): Observable<GetEventNodeResponse>;

  getUserEvent(request: GetUserEventQuery): Observable<GetUserEventResponse>;

  getUserParticipateEvent(request: GetUserParticipateEventQuery): Observable<GetUserParticipateEventResponse>;

  getUserWishEvent(request: GetUserWishEventQuery): Observable<GetUserWishEventResponse>;

  getEventParticipants(request: GetEventParticipantsQuery): Observable<GetEventParticipantsResponse>;

  adminGetUserEvent(request: AdminGetUserEventQuery): Observable<AdminGetUserEventResponse>;

  adminGetUserParticipateEvent(
    request: AdminGetUserParticipateEventQuery,
  ): Observable<AdminGetUserParticipateEventResponse>;

  adminGetUserWishEvent(request: AdminGetUserWishEventQuery): Observable<AdminGetUserWishEventResponse>;
}

export interface ParticipationQueryServiceController {
  getEventNode(
    request: GetSocialEventQuery,
  ): Promise<GetEventNodeResponse> | Observable<GetEventNodeResponse> | GetEventNodeResponse;

  getUserEvent(
    request: GetUserEventQuery,
  ): Promise<GetUserEventResponse> | Observable<GetUserEventResponse> | GetUserEventResponse;

  getUserParticipateEvent(
    request: GetUserParticipateEventQuery,
  ):
    | Promise<GetUserParticipateEventResponse>
    | Observable<GetUserParticipateEventResponse>
    | GetUserParticipateEventResponse;

  getUserWishEvent(
    request: GetUserWishEventQuery,
  ): Promise<GetUserWishEventResponse> | Observable<GetUserWishEventResponse> | GetUserWishEventResponse;

  getEventParticipants(
    request: GetEventParticipantsQuery,
  ): Promise<GetEventParticipantsResponse> | Observable<GetEventParticipantsResponse> | GetEventParticipantsResponse;

  adminGetUserEvent(
    request: AdminGetUserEventQuery,
  ): Promise<AdminGetUserEventResponse> | Observable<AdminGetUserEventResponse> | AdminGetUserEventResponse;

  adminGetUserParticipateEvent(
    request: AdminGetUserParticipateEventQuery,
  ):
    | Promise<AdminGetUserParticipateEventResponse>
    | Observable<AdminGetUserParticipateEventResponse>
    | AdminGetUserParticipateEventResponse;

  adminGetUserWishEvent(
    request: AdminGetUserWishEventQuery,
  ): Promise<AdminGetUserWishEventResponse> | Observable<AdminGetUserWishEventResponse> | AdminGetUserWishEventResponse;
}

export function ParticipationQueryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getEventNode",
      "getUserEvent",
      "getUserParticipateEvent",
      "getUserWishEvent",
      "getEventParticipants",
      "adminGetUserEvent",
      "adminGetUserParticipateEvent",
      "adminGetUserWishEvent",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ParticipationQueryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ParticipationQueryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PARTICIPATION_QUERY_SERVICE_NAME = "ParticipationQueryService";

export interface EventPostLinkCommandServiceClient {
  linkPostToEvent(request: LinkPostToEventCommand): Observable<LinkPostToEventResponse>;

  unlinkPostFromEvent(request: UnlinkPostFromEventCommand): Observable<UnlinkPostFromEventResponse>;
}

export interface EventPostLinkCommandServiceController {
  linkPostToEvent(
    request: LinkPostToEventCommand,
  ): Promise<LinkPostToEventResponse> | Observable<LinkPostToEventResponse> | LinkPostToEventResponse;

  unlinkPostFromEvent(
    request: UnlinkPostFromEventCommand,
  ): Promise<UnlinkPostFromEventResponse> | Observable<UnlinkPostFromEventResponse> | UnlinkPostFromEventResponse;
}

export function EventPostLinkCommandServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["linkPostToEvent", "unlinkPostFromEvent"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("EventPostLinkCommandService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("EventPostLinkCommandService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EVENT_POST_LINK_COMMAND_SERVICE_NAME = "EventPostLinkCommandService";

export interface EventPostLinkQueryServiceClient {
  getEventRelatedToPost(request: GetEventRelatedToPostQuery): Observable<GetEventRelatedToPostResponse>;

  getEventsRelatedToPosts(request: GetEventsRelatedToPostsQuery): Observable<GetEventsRelatedToPostsResponse>;

  getEventPosts(request: GetEventPostsQuery): Observable<GetEventPostsResponse>;
}

export interface EventPostLinkQueryServiceController {
  getEventRelatedToPost(
    request: GetEventRelatedToPostQuery,
  ): Promise<GetEventRelatedToPostResponse> | Observable<GetEventRelatedToPostResponse> | GetEventRelatedToPostResponse;

  getEventsRelatedToPosts(
    request: GetEventsRelatedToPostsQuery,
  ):
    | Promise<GetEventsRelatedToPostsResponse>
    | Observable<GetEventsRelatedToPostsResponse>
    | GetEventsRelatedToPostsResponse;

  getEventPosts(
    request: GetEventPostsQuery,
  ): Promise<GetEventPostsResponse> | Observable<GetEventPostsResponse> | GetEventPostsResponse;
}

export function EventPostLinkQueryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getEventRelatedToPost", "getEventsRelatedToPosts", "getEventPosts"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("EventPostLinkQueryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("EventPostLinkQueryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EVENT_POST_LINK_QUERY_SERVICE_NAME = "EventPostLinkQueryService";
