// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/social/social.responses.proto

/* eslint-disable */
import { PaginationResponse } from "../common/pagination.js";

export interface CreateUserNodeResponse {
}

export interface DeleteUserNodeResponse {
}

export interface GetUserNodeResponse {
  exists: boolean;
}

export interface PostFollowUserResponse {
}

export interface DeleteFollowUserResponse {
}

export interface PostBlockUserResponse {
}

export interface DeleteBlockUserResponse {
}

export interface GetMyFollowsResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetMyFollowersResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetMyBlocksResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetWhoBlockedMeResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface CreatePostNodeResponse {
}

export interface DeletePostNodeResponse {
}

export interface PostUserOwnResponse {
}

export interface DeleteUserOwnResponse {
}

export interface GetPostNodeResponse {
  exists: boolean;
}

export interface GetUserPostsResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetFeedResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface PostLikePostResponse {
}

export interface DeleteLikePostResponse {
}

export interface GetUserLikesResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetPostLikersResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface CreateEventNodeResponse {
}

export interface DeleteEventNodeResponse {
}

export interface PostUserEventResponse {
}

export interface DeleteUserEventResponse {
}

export interface PostUserParticipateEventResponse {
}

export interface DeleteUserParticipateEventResponse {
}

export interface GetUserEventResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetUserParticipateEventResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetEventParticipantsResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface LinkPostToEventResponse {
}

export interface UnlinkPostFromEventResponse {
}

export interface GetEventRelatedToPostResponse {
  eventId: string;
}

export interface GetEventPostsResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}
