// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.13.0
//   protoc               unknown
// source: volontariapp/user/user.command.proto

/* eslint-disable */
import { OrganisationInfo } from "./user.js";

export interface SignUpCommand {
  email: string;
  password: string;
  phone?: string | undefined;
  pseudo?: string | undefined;
  bio?:
    | string
    | undefined;
  /**
   * Deprecated: avatars are attached through avatar_file_id after sign-up.
   *
   * @deprecated
   */
  logoPath?: string | undefined;
  organisationInfo?: OrganisationInfo | undefined;
}

export interface UpdateUserCommand {
  email?: string | undefined;
  previousPassword?: string | undefined;
  newPassword?: string | undefined;
  phone?: string | undefined;
  pseudo?: string | undefined;
  bio?:
    | string
    | undefined;
  /**
   * Deprecated: use avatar_file_id.
   *
   * @deprecated
   */
  logoPath?: string | undefined;
  organisationInfo?: OrganisationInfo | undefined;
  avatarFileId?: string | undefined;
}

export interface DeleteUserCommand {
}

export interface AdminUpdateUserCommand {
  userId: string;
  email?: string | undefined;
  previousPassword?: string | undefined;
  newPassword?: string | undefined;
  phone?: string | undefined;
  pseudo?: string | undefined;
  bio?: string | undefined;
  logoPath?: string | undefined;
  organisationInfo?: OrganisationInfo | undefined;
}

export interface AdminDeleteUserCommand {
  userId: string;
}

export interface LoginCommand {
  email: string;
  password: string;
}

export interface RefreshTokenCommand {
  refreshToken: string;
}

export interface IncrementImpactScoreCommand {
  userId: string;
  scoreIncrement: number;
}

export interface CreateBadgeCommand {
  name: string;
  slug: string;
  /**
   * Deprecated: use icon_file_id.
   *
   * @deprecated
   */
  iconPath?: string | undefined;
  description: string;
  iconFileId?: string | undefined;
  idempotencyKey: string;
}

export interface DeleteBadgeCommand {
  badgeId: string;
}

export interface UpdateBadgeCommand {
  badgeId: string;
  name?: string | undefined;
  slug?:
    | string
    | undefined;
  /**
   * Deprecated: use icon_file_id.
   *
   * @deprecated
   */
  iconPath?: string | undefined;
  description?: string | undefined;
  iconFileId?: string | undefined;
}

export interface AddBadgeToUserCommand {
  userId: string;
  badgeId: string;
}

export interface RemoveBadgeFromUserCommand {
  userId: string;
  badgeId: string;
}
