// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/user/user.command.proto

export interface CreateUserCommand {
  email: string;
  firstName: string;
  lastName: string;
  password: string;
  role: string;
}

export interface UpdateUserCommand {
  id: string;
  email?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  role?: string | undefined;
}

export interface DeleteUserCommand {
  id: string;
}
