// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/user/user.responses.proto

/* eslint-disable */
import { PaginationResponse } from "../common/pagination.js";
import { User } from "./user.js";

export interface UserResponse {
  user: User | undefined;
}

export interface SignUpResponse {
  user: User | undefined;
  auth: AuthResponse | undefined;
}

export interface ListUsersResponse {
  users: User[];
  pagination: PaginationResponse | undefined;
}

export interface UpdateUserResponse {
}

export interface DeleteUserResponse {
}

export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
}

export interface LoginResponse {
  auth: AuthResponse | undefined;
}

export interface RefreshTokenResponse {
  auth: AuthResponse | undefined;
}
