// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.13.0
//   protoc               unknown
// source: volontariapp/user/user.proto

/* eslint-disable */
import { Timestamp } from "../google/protobuf/timestamp.js";

export interface OrganisationInfo {
  rna: string;
}

export interface Badge {
  id: string;
  name: string;
  slug: string;
  /**
   * Deprecated: use icon_file_id.
   *
   * @deprecated
   */
  iconPath?: string | undefined;
  description: string;
  awardedAt: Timestamp | undefined;
  iconFileId?: string | undefined;
}

export interface User {
  id: string;
  email: string;
  pseudo: string;
  bio?: string | undefined;
  role: string;
  /**
   * Deprecated: use avatar_file_id.
   *
   * @deprecated
   */
  logoPath?: string | undefined;
  totalImpactScore: number;
  organisationInfo?: OrganisationInfo | undefined;
  badges: Badge[];
  avatarFileId?: string | undefined;
}

export interface UserPublic {
  id: string;
  pseudo: string;
  bio?:
    | string
    | undefined;
  /**
   * Deprecated: use avatar_file_id.
   *
   * @deprecated
   */
  logoPath?: string | undefined;
  totalImpactScore: number;
  organisationInfo?: OrganisationInfo | undefined;
  badges: Badge[];
  avatarFileId?: string | undefined;
}
