// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/user/user.command.proto

/* eslint-disable */
import { OrganisationInfo } from "./user.js";

export interface SignUpCommand {
  email: string;
  password: string;
  phone?: string | undefined;
  pseudo?: string | undefined;
  bio?: string | undefined;
  logoPath?: string | undefined;
  organisationInfo?: OrganisationInfo | undefined;
}

export interface UpdateUserCommand {
  userId: string;
  email?: string | undefined;
  previousPassword?: string | undefined;
  newPassword?: string | undefined;
  phone?: string | undefined;
  pseudo?: string | undefined;
  bio?: string | undefined;
  logoPath?: string | undefined;
  organisationInfo?: OrganisationInfo | undefined;
}

export interface DeleteUserCommand {
  userId: string;
}

export interface LoginCommand {
  email: string;
  password: string;
}

export interface RefreshTokenCommand {
  refreshToken: string;
}
