// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/user/user.query.proto

/* eslint-disable */
import { PaginationRequest } from '../common/pagination.js';

export interface GetUserQuery {}

export interface AdminGetUserQuery {
  userId: string;
}

export interface ListUsersQuery {
  pagination: PaginationRequest | undefined;
}

export interface GetBadgeQuery {
  badgeId: string;
}

export interface ListBadgesQuery {
  pagination: PaginationRequest | undefined;
}

export interface GetBadgeBySlugQuery {
  slug: string;
}
