// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/user/user.services.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import {
  DeleteUserCommand,
  LoginCommand,
  RefreshTokenCommand,
  SignUpCommand,
  UpdateUserCommand,
} from "./user.command.js";
import { GetUserQuery, ListUsersQuery } from "./user.query.js";
import {
  DeleteUserResponse,
  ListUsersResponse,
  LoginResponse,
  RefreshTokenResponse,
  SignUpResponse,
  UpdateUserResponse,
  UserResponse,
} from "./user.responses.js";

export interface UserServiceClient {
  getUser(request: GetUserQuery): Observable<UserResponse>;

  listUsers(request: ListUsersQuery): Observable<ListUsersResponse>;

  signUp(request: SignUpCommand): Observable<SignUpResponse>;

  updateUser(request: UpdateUserCommand): Observable<UpdateUserResponse>;

  deleteUser(request: DeleteUserCommand): Observable<DeleteUserResponse>;

  login(request: LoginCommand): Observable<LoginResponse>;

  refreshToken(request: RefreshTokenCommand): Observable<RefreshTokenResponse>;
}

export interface UserServiceController {
  getUser(request: GetUserQuery): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  listUsers(request: ListUsersQuery): Promise<ListUsersResponse> | Observable<ListUsersResponse> | ListUsersResponse;

  signUp(request: SignUpCommand): Promise<SignUpResponse> | Observable<SignUpResponse> | SignUpResponse;

  updateUser(
    request: UpdateUserCommand,
  ): Promise<UpdateUserResponse> | Observable<UpdateUserResponse> | UpdateUserResponse;

  deleteUser(
    request: DeleteUserCommand,
  ): Promise<DeleteUserResponse> | Observable<DeleteUserResponse> | DeleteUserResponse;

  login(request: LoginCommand): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  refreshToken(
    request: RefreshTokenCommand,
  ): Promise<RefreshTokenResponse> | Observable<RefreshTokenResponse> | RefreshTokenResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getUser",
      "listUsers",
      "signUp",
      "updateUser",
      "deleteUser",
      "login",
      "refreshToken",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
