// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/post/v1/post.proto

/* eslint-disable */
import type { PaginationRequest, PaginationResponse } from "../../common/v1/pagination";

export const protobufPackage = "volontariapp.post.v1";

/** trigger ci */

export interface Post {
  id: string;
  authorId: string;
  title: string;
  content: string;
}

export interface GetPostRequest {
  id: string;
}

export interface GetPostResponse {
  post: Post | undefined;
}

export interface CreatePostResponse {
  post: Post | undefined;
}

export interface UpdatePostResponse {
  post: Post | undefined;
}

export interface ListPostsRequest {
  pagination: PaginationRequest | undefined;
  authorId?: string | undefined;
}

export interface ListPostsResponse {
  posts: Post[];
  pagination: PaginationResponse | undefined;
}

export interface CreatePostRequest {
  authorId: string;
  title: string;
  content: string;
}

export interface UpdatePostRequest {
  id: string;
  title?: string | undefined;
  content?: string | undefined;
}

export interface DeletePostRequest {
  id: string;
}

export interface DeletePostResponse {
  success: boolean;
}

export type PostServiceDefinition = typeof PostServiceDefinition;
export const PostServiceDefinition = {
  name: "PostService",
  fullName: "volontariapp.post.v1.PostService",
  methods: {
    getPost: {
      name: "GetPost",
      requestType: GetPostRequest,
      requestStream: false,
      responseType: GetPostResponse,
      responseStream: false,
      options: {},
    },
    listPosts: {
      name: "ListPosts",
      requestType: ListPostsRequest,
      requestStream: false,
      responseType: ListPostsResponse,
      responseStream: false,
      options: {},
    },
    createPost: {
      name: "CreatePost",
      requestType: CreatePostRequest,
      requestStream: false,
      responseType: CreatePostResponse,
      responseStream: false,
      options: {},
    },
    updatePost: {
      name: "UpdatePost",
      requestType: UpdatePostRequest,
      requestStream: false,
      responseType: UpdatePostResponse,
      responseStream: false,
      options: {},
    },
    deletePost: {
      name: "DeletePost",
      requestType: DeletePostRequest,
      requestStream: false,
      responseType: DeletePostResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;
