// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/event/v1/event.proto

/* eslint-disable */
import type { PaginationRequest, PaginationResponse } from "../../common/v1/pagination";

export const protobufPackage = "volontariapp.event.v1";

/** trigger ci */

export interface Event {
  id: string;
  title: string;
  description: string;
  startDate: Date | undefined;
  endDate: Date | undefined;
  location: string;
  organizerId: string;
}

export interface GetEventRequest {
  id: string;
}

export interface GetEventResponse {
  event: Event | undefined;
}

export interface CreateEventResponse {
  event: Event | undefined;
}

export interface UpdateEventResponse {
  event: Event | undefined;
}

export interface ListEventsRequest {
  pagination: PaginationRequest | undefined;
}

export interface ListEventsResponse {
  events: Event[];
  pagination: PaginationResponse | undefined;
}

export interface CreateEventRequest {
  title: string;
  description: string;
  startDate: Date | undefined;
  endDate: Date | undefined;
  location: string;
  organizerId: string;
}

export interface UpdateEventRequest {
  id: string;
  title?: string | undefined;
  description?: string | undefined;
  startDate?: Date | undefined;
  endDate?: Date | undefined;
  location?: string | undefined;
}

export interface DeleteEventRequest {
  id: string;
}

export interface DeleteEventResponse {
  success: boolean;
}

export type EventServiceDefinition = typeof EventServiceDefinition;
export const EventServiceDefinition = {
  name: "EventService",
  fullName: "volontariapp.event.v1.EventService",
  methods: {
    getEvent: {
      name: "GetEvent",
      requestType: GetEventRequest,
      requestStream: false,
      responseType: GetEventResponse,
      responseStream: false,
      options: {},
    },
    listEvents: {
      name: "ListEvents",
      requestType: ListEventsRequest,
      requestStream: false,
      responseType: ListEventsResponse,
      responseStream: false,
      options: {},
    },
    createEvent: {
      name: "CreateEvent",
      requestType: CreateEventRequest,
      requestStream: false,
      responseType: CreateEventResponse,
      responseStream: false,
      options: {},
    },
    updateEvent: {
      name: "UpdateEvent",
      requestType: UpdateEventRequest,
      requestStream: false,
      responseType: UpdateEventResponse,
      responseStream: false,
      options: {},
    },
    deleteEvent: {
      name: "DeleteEvent",
      requestType: DeleteEventRequest,
      requestStream: false,
      responseType: DeleteEventResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;
