// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/user/user.proto

/* eslint-disable */
import { Timestamp } from "../google/protobuf/timestamp.js";

export interface OrganisationInfo {
  rna: string;
}

export interface Badge {
  id: string;
  name: string;
  slug: string;
  iconPath?: string | undefined;
  description: string;
  awardedAt: Timestamp | undefined;
}

export interface User {
  id: string;
  email: string;
  pseudo: string;
  bio?: string | undefined;
  role: string;
  logoPath?: string | undefined;
  totalImpactScore: number;
  organisationInfo?: OrganisationInfo | undefined;
  badges: Badge[];
}
