// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/user/user.requests.proto

/* eslint-disable */
import { PaginationRequest } from "../common/pagination.js";

export interface GetUserRequest {
  id: string;
}

export interface ListUsersRequest {
  pagination: PaginationRequest | undefined;
}

export interface CreateUserRequest {
  email: string;
  firstName: string;
  lastName: string;
  password: string;
  role: string;
}

export interface UpdateUserRequest {
  id: string;
  email?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  role?: string | undefined;
}

export interface DeleteUserRequest {
  id: string;
}
