// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/user/user.proto

/* eslint-disable */

export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: string;
}
