// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/user/user.responses.proto

/* eslint-disable */
import { PaginationResponse } from "../common/pagination.js";
import { User } from "./user.js";

export interface GetUserResponse {
  user: User | undefined;
}

export interface CreateUserResponse {
  user: User | undefined;
}

export interface UpdateUserResponse {
  user: User | undefined;
}

export interface ListUsersResponse {
  users: User[];
  pagination: PaginationResponse | undefined;
}

export interface DeleteUserResponse {
  success: boolean;
}
