// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/user/user.query.proto

/* eslint-disable */
import { PaginationRequest } from "../common/pagination.js";

export interface UserQuery {
  id: string;
}

export interface ListUsersQuery {
  pagination: PaginationRequest | undefined;
}
