// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: volontariapp/user/user.responses.proto

/* eslint-disable */
import { PaginationResponse } from "../common/pagination.js";
import { Badge, User, UserPublic } from "./user.js";

export interface UserResponse {
  user: User | undefined;
}

export interface PublicUserResponse {
  userPublic: UserPublic | undefined;
}

export interface AdminUserResponse {
  user: User | undefined;
}

export interface SignUpResponse {
  user: User | undefined;
  auth: AuthResponse | undefined;
}

export interface ListUsersResponse {
  users: User[];
  pagination: PaginationResponse | undefined;
}

export interface GetUsersByIdsResponse {
  users: User[];
  pagination: PaginationResponse | undefined;
}

export interface GetMyFollowsProfilesResponse {
  users: User[];
  pagination: PaginationResponse | undefined;
}

export interface GetMyFollowersProfilesResponse {
  users: User[];
  pagination: PaginationResponse | undefined;
}

export interface GetEventParticipantsProfilesResponse {
  users: UserPublic[];
  pagination: PaginationResponse | undefined;
}

export interface GetPostLikersProfilesResponse {
  users: UserPublic[];
  pagination: PaginationResponse | undefined;
}

export interface UpdateUserResponse {
}

export interface AdminUpdateUserResponse {
}

export interface DeleteUserResponse {
}

export interface AdminDeleteUserResponse {
}

export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
}

export interface LoginResponse {
  auth: AuthResponse | undefined;
}

export interface RefreshTokenResponse {
  auth: AuthResponse | undefined;
}

export interface IncrementImpactScoreResponse {
}

export interface CreateBadgeResponse {
  badge: Badge | undefined;
}

export interface UpdateBadgeResponse {
}

export interface DeleteBadgeResponse {
}

export interface AddBadgeToUserResponse {
}

export interface RemoveBadgeFromUserResponse {
}

export interface BadgeResponse {
  badge: Badge | undefined;
}

export interface GetBadgeBySlugResponse {
  badge: Badge | undefined;
}

export interface ListBadgesResponse {
  badges: Badge[];
  pagination: PaginationResponse | undefined;
}
