// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/social/social.proto

export interface SocialUser {
  userId: string;
}

export interface SocialPost {
  postId: string;
}

export interface SocialEvent {
  eventId: string;
}
