// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: volontariapp/social/social.responses.proto

/* eslint-disable */
import { PaginationResponse } from "../common/pagination.js";

export interface CreateUserNodeResponse {
}

export interface DeleteUserNodeResponse {
}

export interface GetUserNodeResponse {
  exists: boolean;
}

export interface PostFollowUserResponse {
}

export interface AdminPostFollowUserResponse {
}

export interface DeleteFollowUserResponse {
}

export interface AdminDeleteFollowUserResponse {
}

export interface PostBlockUserResponse {
}

export interface AdminPostBlockUserResponse {
}

export interface DeleteBlockUserResponse {
}

export interface AdminDeleteBlockUserResponse {
}

export interface GetMyFollowsResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface AdminGetMyFollowsResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetMyFollowersResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface AdminGetMyFollowersResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetMyBlocksResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface AdminGetMyBlocksResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetWhoBlockedMeResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface AdminGetWhoBlockedMeResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface CreatePostNodeResponse {
}

export interface DeletePostNodeResponse {
}

export interface PostUserOwnResponse {
}

export interface AdminPostUserOwnResponse {
}

export interface DeleteUserOwnResponse {
}

export interface AdminDeleteUserOwnResponse {
}

export interface GetPostNodeResponse {
  exists: boolean;
}

export interface GetUserPostsResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface AdminGetUserPostsResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetFeedResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface AdminGetFeedResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface PostLikePostResponse {
}

export interface AdminPostLikePostResponse {
}

export interface DeleteLikePostResponse {
}

export interface AdminDeleteLikePostResponse {
}

export interface GetUserLikesResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface AdminGetUserLikesResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetPostLikersResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface CreateEventNodeResponse {
}

export interface DeleteEventNodeResponse {
}

export interface PostUserEventResponse {
}

export interface DeleteUserEventResponse {
}

export interface PostUserParticipateEventResponse {
}

export interface AdminPostUserParticipateEventResponse {
}

export interface DeleteUserParticipateEventResponse {
}

export interface AdminDeleteUserParticipateEventResponse {
}

export interface PostUserWishEventResponse {
}

export interface AdminPostUserWishEventResponse {
}

export interface DeleteUserWishEventResponse {
}

export interface AdminDeleteUserWishEventResponse {
}

export interface GetUserEventResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface AdminGetUserEventResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetUserParticipateEventResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface AdminGetUserParticipateEventResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetUserWishEventResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface AdminGetUserWishEventResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetEventParticipantsResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface LinkPostToEventResponse {
}

export interface UnlinkPostFromEventResponse {
}

export interface GetEventRelatedToPostResponse {
  eventId: string;
}

export interface EventPostLink {
  postId: string;
  eventId: string;
}

export interface GetEventsRelatedToPostsResponse {
  links: EventPostLink[];
}

export interface GetEventPostsResponse {
  ids: string[];
  pagination: PaginationResponse | undefined;
}

export interface GetEventNodeResponse {
  exists: boolean;
}
