// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/common/timestamp.proto

/* eslint-disable */
import { Timestamp } from "../google/protobuf/timestamp.js";

export interface DateRange {
  start: Timestamp | undefined;
  end: Timestamp | undefined;
}
