// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/event/event.responses.proto

/* eslint-disable */
import { PaginationResponse } from "../common/pagination.js";
import { Event } from "./event.js";

export interface GetEventResponse {
  event: Event | undefined;
}

export interface CreateEventResponse {
  event: Event | undefined;
}

export interface UpdateEventResponse {
  event: Event | undefined;
}

export interface ListEventsResponse {
  events: Event[];
  pagination: PaginationResponse | undefined;
}

export interface DeleteEventResponse {
  success: boolean;
}
