// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/event/event.requests.proto

/* eslint-disable */
import { wrappers } from "protobufjs";
import { PaginationRequest } from "../common/pagination.js";

export interface GetEventRequest {
  id: string;
}

export interface ListEventsRequest {
  pagination: PaginationRequest | undefined;
}

export interface CreateEventRequest {
  title: string;
  description: string;
  startDate: Date | undefined;
  endDate: Date | undefined;
  location: string;
  organizerId: string;
}

export interface UpdateEventRequest {
  id: string;
  title?: string | undefined;
  description?: string | undefined;
  startDate?: Date | undefined;
  endDate?: Date | undefined;
  location?: string | undefined;
}

export interface DeleteEventRequest {
  id: string;
}

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;
