// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/event/event.responses.proto

/* eslint-disable */
import { Event, Requirement, Tag } from "./event.js";

/** Unique Responses for Command Service */
export interface CreateEventResponse {
  event: Event | undefined;
}

export interface UpdateEventResponse {
  event: Event | undefined;
}

export interface ChangeEventStateResponse {
  event: Event | undefined;
}

export interface ManageRequirementsResponse {
  success: boolean;
  message: string;
}

export interface GetEventResponse {
  event: Event | undefined;
}

export interface SearchEventsResponse {
  events: Event[];
  totalCount: number;
}

export interface ListRequirementsResponse {
  requirements: Requirement[];
}

export interface GetTagsResponse {
  tags: Tag[];
}

export interface CreateTagResponse {
  tag: Tag | undefined;
}
