// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/event/event.services.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import {
  CreateEventRequest,
  DeleteEventRequest,
  GetEventRequest,
  ListEventsRequest,
  UpdateEventRequest,
} from "./event.requests.js";
import {
  CreateEventResponse,
  DeleteEventResponse,
  GetEventResponse,
  ListEventsResponse,
  UpdateEventResponse,
} from "./event.responses.js";

export interface EventServiceClient {
  getEvent(request: GetEventRequest): Observable<GetEventResponse>;

  listEvents(request: ListEventsRequest): Observable<ListEventsResponse>;

  createEvent(request: CreateEventRequest): Observable<CreateEventResponse>;

  updateEvent(request: UpdateEventRequest): Observable<UpdateEventResponse>;

  deleteEvent(request: DeleteEventRequest): Observable<DeleteEventResponse>;
}

export interface EventServiceController {
  getEvent(request: GetEventRequest): Promise<GetEventResponse> | Observable<GetEventResponse> | GetEventResponse;

  listEvents(
    request: ListEventsRequest,
  ): Promise<ListEventsResponse> | Observable<ListEventsResponse> | ListEventsResponse;

  createEvent(
    request: CreateEventRequest,
  ): Promise<CreateEventResponse> | Observable<CreateEventResponse> | CreateEventResponse;

  updateEvent(
    request: UpdateEventRequest,
  ): Promise<UpdateEventResponse> | Observable<UpdateEventResponse> | UpdateEventResponse;

  deleteEvent(
    request: DeleteEventRequest,
  ): Promise<DeleteEventResponse> | Observable<DeleteEventResponse> | DeleteEventResponse;
}

export function EventServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getEvent", "listEvents", "createEvent", "updateEvent", "deleteEvent"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("EventService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("EventService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EVENT_SERVICE_NAME = "EventService";
