// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/event/event.proto

/* eslint-disable */
import _m0 from 'protobufjs'; const { wrappers } = _m0;

export interface Event {
  id: string;
  title: string;
  description: string;
  startDate: Date | undefined;
  endDate: Date | undefined;
  location: string;
  organizerId: string;
}

wrappers['.google.protobuf.Timestamp'] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;
