// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/event/event.query.proto

/* eslint-disable */
import { PaginationRequest } from "../common/pagination.js";

export interface EventQuery {
  id: string;
}

export interface ListEventsQuery {
  pagination: PaginationRequest | undefined;
}
