// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: volontariapp/event/event.query.proto

/* eslint-disable */
import { GeoCircle } from "../common/geo.js";
import { PaginationRequest } from "../common/pagination.js";
import { EventState, EventType } from "./event.js";

export interface GetEventQuery {
  id: string;
}

export interface SearchEventsQuery {
  area: GeoCircle | undefined;
  types: EventType[];
  tagSlugs: string[];
  onlyAvailable: boolean;
  searchTerm: string;
  organizerId: string;
  ids: string[];
  excludedIds: string[];
  startDateFrom?: string | undefined;
  startDateTo?: string | undefined;
  statuses: EventState[];
  pagination: PaginationRequest | undefined;
}

export interface GetEventsByIdsQuery {
  ids: string[];
}

export interface ListRequirementsQuery {
  eventId: string;
}

export interface GetTagsQuery {
  slugs: string[];
}

export interface GetUserCreatedEventsQuery {
  pagination: PaginationRequest | undefined;
}

export interface GetUserParticipatedEventsQuery {
  pagination: PaginationRequest | undefined;
}

export interface GetUserWishedEventsQuery {
  pagination: PaginationRequest | undefined;
}
