// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/event/event.proto

/* eslint-disable */
import { Timestamp } from '..//google/protobuf/timestamp.js';
import { Point } from '../common/geo.js';

export enum EventType {
  EVENT_TYPE_UNSPECIFIED = 0,
  EVENT_TYPE_SOCIAL = 1,
  EVENT_TYPE_ECOLOGY = 2,
  UNRECOGNIZED = -1,
}

export enum EventState {
  EVENT_STATE_UNSPECIFIED = 0,
  EVENT_STATE_DRAFT = 1,
  EVENT_STATE_PUBLISHED = 2,
  EVENT_STATE_CANCELLED = 3,
  UNRECOGNIZED = -1,
}

export interface Tag {
  id: string;
  slug: string;
  name: string;
  color: string;
}

export interface Requirement {
  id: string;
  name: string;
  description: string;
  neededQuantity: number;
  currentQuantity: number;
}

export interface Event {
  id: string;
  title: string;
  description: string;
  startAt: Timestamp | undefined;
  endAt: Timestamp | undefined;
  location: Point | undefined;
  localisationName: string;
  type: EventType;
  state: EventState;
  awardedImpactScore: number;
  maxParticipants: number;
  currentParticipants: number;
  organizerId: string;
  tags: Tag[];
  requirements: Requirement[];
}
