// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.13.0
//   protoc               unknown
// source: volontariapp/storage/storage.responses.proto

/* eslint-disable */
import { Timestamp } from "../google/protobuf/timestamp.js";
import { FileMetadata } from "./storage.js";

export interface GenerateUploadUrlResponse {
  fileId: string;
  uploadUrl: string;
  expiresAt:
    | Timestamp
    | undefined;
  /** Fields of the signed POST form. */
  uploadFields: { [key: string]: string };
}

export interface GenerateUploadUrlResponse_UploadFieldsEntry {
  key: string;
  value: string;
}

export interface ConfirmUploadResponse {
  /** SCANNING (ASYNC) or final state (SYNC). */
  file: FileMetadata | undefined;
}

export interface ConfirmFileAttachmentResponse {
  success: boolean;
  updatedCount: number;
  files: FileMetadata[];
}

export interface DeleteFileResponse {
  success: boolean;
}

export interface FileMetadataResponse {
  file: FileMetadata | undefined;
}

export interface VerifyFilesExistResponse {
  allExist: boolean;
  missingFileIds: string[];
}
