// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: volontariapp/storage/storage.query.proto

/* eslint-disable */

export interface GetFileMetadataQuery {
  fileId: string;
}
