// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.13.0
//   protoc               unknown
// source: volontariapp/storage/storage.command.proto

/* eslint-disable */
import { EntityType } from "./storage.js";

export interface GenerateUploadUrlCommand {
  mimeType: string;
  sizeBytes: number;
  entityType: EntityType;
  /**
   * Deprecated: ignored, visibility is derived from the scan result.
   *
   * @deprecated
   */
  isPublic: boolean;
}

export interface ConfirmUploadCommand {
  fileId: string;
}

export interface ConfirmFileAttachmentCommand {
  fileIds: string[];
  entityType: EntityType;
  entityId: string;
}

export interface DeleteFileCommand {
  fileId: string;
}
