// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: volontariapp/storage/storage.services.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { ConfirmFileAttachmentCommand, DeleteFileCommand, GenerateUploadUrlCommand } from "./storage.command.js";
import { GetFileMetadataQuery } from "./storage.query.js";
import {
  ConfirmFileAttachmentResponse,
  DeleteFileResponse,
  FileMetadataResponse,
  GenerateUploadUrlResponse,
} from "./storage.responses.js";

export interface StorageServiceClient {
  generateUploadUrl(request: GenerateUploadUrlCommand): Observable<GenerateUploadUrlResponse>;

  confirmFileAttachment(request: ConfirmFileAttachmentCommand): Observable<ConfirmFileAttachmentResponse>;

  deleteFile(request: DeleteFileCommand): Observable<DeleteFileResponse>;

  getFileMetadata(request: GetFileMetadataQuery): Observable<FileMetadataResponse>;
}

export interface StorageServiceController {
  generateUploadUrl(
    request: GenerateUploadUrlCommand,
  ): Promise<GenerateUploadUrlResponse> | Observable<GenerateUploadUrlResponse> | GenerateUploadUrlResponse;

  confirmFileAttachment(
    request: ConfirmFileAttachmentCommand,
  ): Promise<ConfirmFileAttachmentResponse> | Observable<ConfirmFileAttachmentResponse> | ConfirmFileAttachmentResponse;

  deleteFile(
    request: DeleteFileCommand,
  ): Promise<DeleteFileResponse> | Observable<DeleteFileResponse> | DeleteFileResponse;

  getFileMetadata(
    request: GetFileMetadataQuery,
  ): Promise<FileMetadataResponse> | Observable<FileMetadataResponse> | FileMetadataResponse;
}

export function StorageServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["generateUploadUrl", "confirmFileAttachment", "deleteFile", "getFileMetadata"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("StorageService", method)(constructor.prototype[method], method, descriptor);
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("StorageService", method)(constructor.prototype[method], method, descriptor);
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
  };
}

export const STORAGE_SERVICE_NAME = "StorageService";
