// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: volontariapp/storage/storage.command.proto

/* eslint-disable */
import { EntityType } from "./storage.js";

export interface GenerateUploadUrlCommand {
  mimeType: string;
  sizeBytes: number;
  entityType: EntityType;
  isPublic: boolean;
}

export interface ConfirmFileAttachmentCommand {
  fileIds: string[];
  entityType: EntityType;
  entityId: string;
}

export interface DeleteFileCommand {
  fileId: string;
}
