// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: volontariapp/post/comment.proto

/* eslint-disable */
import { Timestamp } from "../google/protobuf/timestamp.js";

export interface Comment {
  id: string;
  postId: string;
  authorId: string;
  content: string;
  createdAt: Timestamp | undefined;
  updatedAt: Timestamp | undefined;
}
