// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.13.0
//   protoc               unknown
// source: volontariapp/post/comment.responses.proto

/* eslint-disable */
import { PaginationResponse } from "../common/pagination.js";
import { Comment } from "./comment.js";

export interface CreateCommentResponse {
  comment: Comment | undefined;
}

export interface ListCommentsResponse {
  comments: Comment[];
  pagination: PaginationResponse | undefined;
}

export interface DeleteCommentResponse {
  success: boolean;
}
