// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.13.0
//   protoc               unknown
// source: volontariapp/post/post.proto

/* eslint-disable */
import { Timestamp } from "../google/protobuf/timestamp.js";

export enum PostMediaStatus {
  POST_MEDIA_STATUS_UNSPECIFIED = 0,
  POST_MEDIA_STATUS_NONE = 1,
  POST_MEDIA_STATUS_PENDING = 2,
  POST_MEDIA_STATUS_READY = 3,
  POST_MEDIA_STATUS_REJECTED = 4,
  UNRECOGNIZED = -1,
}

export interface PostMedia {
  fileId: string;
  position: number;
}

export interface Post {
  id: string;
  authorId: string;
  title: string;
  content: string;
  createdAt: Timestamp | undefined;
  updatedAt: Timestamp | undefined;
  eventId?: string | undefined;
  media: PostMedia[];
  mediaStatus: PostMediaStatus;
}
