// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: volontariapp/post/post.query.proto

/* eslint-disable */
import { PaginationRequest } from "../common/pagination.js";

export interface GetPostQuery {
  id: string;
}

export interface ListPostsQuery {
  pagination: PaginationRequest | undefined;
  authorId?: string | undefined;
}
