// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/post/post.command.proto

/* eslint-disable */

export interface CreatePostCommand {
  authorId: string;
  title: string;
  content: string;
}

export interface UpdatePostCommand {
  id: string;
  title?: string | undefined;
  content?: string | undefined;
}

export interface DeletePostCommand {
  id: string;
}
