// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.13.0
//   protoc               unknown
// source: volontariapp/post/post.proto

/* eslint-disable */
import { Timestamp } from "../google/protobuf/timestamp.js";

/**
 * Aggregated processing state of the media attached to a post.
 * Only NONE and READY posts are visible to readers other than the author.
 */
export enum PostMediaStatus {
  POST_MEDIA_STATUS_UNSPECIFIED = 0,
  /** POST_MEDIA_STATUS_NONE - The post has no media. */
  POST_MEDIA_STATUS_NONE = 1,
  /** POST_MEDIA_STATUS_PENDING - At least one media is still being validated. */
  POST_MEDIA_STATUS_PENDING = 2,
  /** POST_MEDIA_STATUS_READY - Every media is CLEAN. */
  POST_MEDIA_STATUS_READY = 3,
  /** POST_MEDIA_STATUS_REJECTED - At least one media was rejected. */
  POST_MEDIA_STATUS_REJECTED = 4,
  UNRECOGNIZED = -1,
}

/**
 * A file attached to a post. The public URL is not part of the contract:
 * the gateway computes it from file_id.
 */
export interface PostMedia {
  fileId: string;
  /** Display order of the media inside the post. */
  position: number;
}

export interface Post {
  id: string;
  authorId: string;
  title: string;
  content: string;
  createdAt: Timestamp | undefined;
  updatedAt: Timestamp | undefined;
  eventId?: string | undefined;
  media: PostMedia[];
  mediaStatus: PostMediaStatus;
}
