// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/post/post.responses.proto

/* eslint-disable */
import { PaginationResponse } from "../common/pagination.js";
import { Post } from "./post.js";

export interface GetPostResponse {
  post: Post | undefined;
}

export interface CreatePostResponse {
  post: Post | undefined;
}

export interface UpdatePostResponse {
  post: Post | undefined;
}

export interface ListPostsResponse {
  posts: Post[];
  pagination: PaginationResponse | undefined;
}

export interface DeletePostResponse {
  success: boolean;
}
