// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/event/event.services.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import {
  ChangeEventStateCommand,
  CreateEventCommand,
  CreateTagCommand,
  ManageRequirementCommand,
  UpdateEventCommand,
} from "./event.command.js";
import { GetEventQuery, GetTagsQuery, ListRequirementsQuery, SearchEventsQuery } from "./event.query.js";
import {
  ChangeEventStateResponse,
  CreateEventResponse,
  CreateTagResponse,
  GetEventResponse,
  GetTagsResponse,
  ListRequirementsResponse,
  ManageRequirementsResponse,
  SearchEventsResponse,
  UpdateEventResponse,
} from "./event.responses.js";

export interface EventCommandServiceClient {
  createEvent(request: CreateEventCommand): Observable<CreateEventResponse>;

  updateEvent(request: UpdateEventCommand): Observable<UpdateEventResponse>;

  changeEventState(request: ChangeEventStateCommand): Observable<ChangeEventStateResponse>;

  manageRequirements(request: ManageRequirementCommand): Observable<ManageRequirementsResponse>;
}

export interface EventCommandServiceController {
  createEvent(
    request: CreateEventCommand,
  ): Promise<CreateEventResponse> | Observable<CreateEventResponse> | CreateEventResponse;

  updateEvent(
    request: UpdateEventCommand,
  ): Promise<UpdateEventResponse> | Observable<UpdateEventResponse> | UpdateEventResponse;

  changeEventState(
    request: ChangeEventStateCommand,
  ): Promise<ChangeEventStateResponse> | Observable<ChangeEventStateResponse> | ChangeEventStateResponse;

  manageRequirements(
    request: ManageRequirementCommand,
  ): Promise<ManageRequirementsResponse> | Observable<ManageRequirementsResponse> | ManageRequirementsResponse;
}

export function EventCommandServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createEvent", "updateEvent", "changeEventState", "manageRequirements"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("EventCommandService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("EventCommandService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EVENT_COMMAND_SERVICE_NAME = "EventCommandService";

export interface EventQueryServiceClient {
  getEvent(request: GetEventQuery): Observable<GetEventResponse>;

  searchEvents(request: SearchEventsQuery): Observable<SearchEventsResponse>;

  listRequirements(request: ListRequirementsQuery): Observable<ListRequirementsResponse>;
}

export interface EventQueryServiceController {
  getEvent(request: GetEventQuery): Promise<GetEventResponse> | Observable<GetEventResponse> | GetEventResponse;

  searchEvents(
    request: SearchEventsQuery,
  ): Promise<SearchEventsResponse> | Observable<SearchEventsResponse> | SearchEventsResponse;

  listRequirements(
    request: ListRequirementsQuery,
  ): Promise<ListRequirementsResponse> | Observable<ListRequirementsResponse> | ListRequirementsResponse;
}

export function EventQueryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getEvent", "searchEvents", "listRequirements"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("EventQueryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("EventQueryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EVENT_QUERY_SERVICE_NAME = "EventQueryService";

export interface TagServiceClient {
  getTags(request: GetTagsQuery): Observable<GetTagsResponse>;

  createTag(request: CreateTagCommand): Observable<CreateTagResponse>;
}

export interface TagServiceController {
  getTags(request: GetTagsQuery): Promise<GetTagsResponse> | Observable<GetTagsResponse> | GetTagsResponse;

  createTag(request: CreateTagCommand): Promise<CreateTagResponse> | Observable<CreateTagResponse> | CreateTagResponse;
}

export function TagServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getTags", "createTag"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TagService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TagService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TAG_SERVICE_NAME = "TagService";
