// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/event/event.query.proto

/* eslint-disable */
import { GeoCircle } from "../common/geo.js";
import { EventType } from "./event.js";

export interface GetEventQuery {
  id: string;
}

export interface SearchEventsQuery {
  area: GeoCircle | undefined;
  types: EventType[];
  tagSlugs: string[];
  onlyAvailable: boolean;
}

export interface ListRequirementsQuery {
  eventId: string;
}

export interface GetTagsQuery {
  slugs: string[];
}
