// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/event/event.command.proto

/* eslint-disable */
import _m0 from "protobufjs"; const { wrappers } = _m0;
import { Point } from "../common/geo.js";
import { Event, EventState, EventType } from "./event.js";

export interface CreateEventCommand {
  title: string;
  description: string;
  startAt: Date | undefined;
  endAt: Date | undefined;
  location: Point | undefined;
  localisationName: string;
  type: EventType;
  awardedImpactScore: number;
  maxParticipants: number;
  tagIds: string[];
}

export interface UpdateEventCommand {
  id: string;
  event: Event | undefined;
  updateMask: string[] | undefined;
}

export interface ChangeEventStateCommand {
  id: string;
  newState: EventState;
}

export interface ManageRequirementCommand {
  eventId: string;
  add?: AddRequirement | undefined;
  remove?: RemoveRequirement | undefined;
}

export interface AddRequirement {
  name: string;
  description: string;
  neededQuantity: number;
}

export interface RemoveRequirement {
  requirementId: string;
}

export interface CreateTagCommand {
  slug: string;
  name: string;
  color: string;
}

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;
