// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/event/event.command.proto

/* eslint-disable */
import { Timestamp } from "../google/protobuf/timestamp.js";
import { Point } from "../common/geo.js";
import { Event, EventState, EventType } from "./event.js";

export interface CreateEventCommand {
  title: string;
  description: string;
  startAt: Timestamp | undefined;
  endAt: Timestamp | undefined;
  location: Point | undefined;
  localisationName: string;
  type: EventType;
  awardedImpactScore: number;
  maxParticipants: number;
  tagIds: string[];
}

export interface UpdateEventCommand {
  id: string;
  event: Event | undefined;
  updateMask: string[];
}

export interface ChangeEventStateCommand {
  id: string;
  newState: EventState;
}

export interface ManageRequirementCommand {
  eventId: string;
  add?: AddRequirement | undefined;
  remove?: RemoveRequirement | undefined;
}

export interface AddRequirement {
  name: string;
  description: string;
  neededQuantity: number;
}

export interface RemoveRequirement {
  requirementId: string;
}

export interface CreateTagCommand {
  slug: string;
  name: string;
  color: string;
}

export interface UpdateTagCommand {
  id: string;
  name: string;
  color: string;
}

export interface DeleteEventCommand {
  id: string;
}

export interface DeleteTagCommand {
  id: string;
}
