// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/event/event.services.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { CreateEventCommand, DeleteEventCommand, UpdateEventCommand } from "./event.command.js";
import { EventQuery, ListEventsQuery } from "./event.query.js";
import {
  CreateEventResponse,
  DeleteEventResponse,
  GetEventResponse,
  ListEventsResponse,
  UpdateEventResponse,
} from "./event.responses.js";

export interface EventServiceClient {
  getEvent(request: EventQuery): Observable<GetEventResponse>;

  listEvents(request: ListEventsQuery): Observable<ListEventsResponse>;

  createEvent(request: CreateEventCommand): Observable<CreateEventResponse>;

  updateEvent(request: UpdateEventCommand): Observable<UpdateEventResponse>;

  deleteEvent(request: DeleteEventCommand): Observable<DeleteEventResponse>;
}

export interface EventServiceController {
  getEvent(request: EventQuery): Promise<GetEventResponse> | Observable<GetEventResponse> | GetEventResponse;

  listEvents(
    request: ListEventsQuery,
  ): Promise<ListEventsResponse> | Observable<ListEventsResponse> | ListEventsResponse;

  createEvent(
    request: CreateEventCommand,
  ): Promise<CreateEventResponse> | Observable<CreateEventResponse> | CreateEventResponse;

  updateEvent(
    request: UpdateEventCommand,
  ): Promise<UpdateEventResponse> | Observable<UpdateEventResponse> | UpdateEventResponse;

  deleteEvent(
    request: DeleteEventCommand,
  ): Promise<DeleteEventResponse> | Observable<DeleteEventResponse> | DeleteEventResponse;
}

export function EventServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getEvent", "listEvents", "createEvent", "updateEvent", "deleteEvent"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("EventService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("EventService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EVENT_SERVICE_NAME = "EventService";
