// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: volontariapp/event/event.services.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import {
  ChangeEventStateCommand,
  CreateEventCommand,
  CreateTagCommand,
  DeleteEventCommand,
  DeleteTagCommand,
  ManageRequirementCommand,
  UpdateEventCommand,
  UpdateTagCommand,
} from "./event.command.js";
import { GetEventQuery, GetTagsQuery, ListRequirementsQuery, SearchEventsQuery } from "./event.query.js";
import {
  ChangeEventStateResponse,
  CreateEventResponse,
  CreateTagResponse,
  DeleteEventResponse,
  DeleteTagResponse,
  GetEventResponse,
  GetTagsResponse,
  ListRequirementsResponse,
  ManageRequirementsResponse,
  SearchEventsResponse,
  UpdateEventResponse,
  UpdateTagResponse,
} from "./event.responses.js";

export interface EventCommandServiceClient {
  createEvent(request: CreateEventCommand): Observable<CreateEventResponse>;

  updateEvent(request: UpdateEventCommand): Observable<UpdateEventResponse>;

  changeEventState(request: ChangeEventStateCommand): Observable<ChangeEventStateResponse>;

  manageRequirements(request: ManageRequirementCommand): Observable<ManageRequirementsResponse>;

  deleteEvent(request: DeleteEventCommand): Observable<DeleteEventResponse>;
}

export interface EventCommandServiceController {
  createEvent(
    request: CreateEventCommand,
  ): Promise<CreateEventResponse> | Observable<CreateEventResponse> | CreateEventResponse;

  updateEvent(
    request: UpdateEventCommand,
  ): Promise<UpdateEventResponse> | Observable<UpdateEventResponse> | UpdateEventResponse;

  changeEventState(
    request: ChangeEventStateCommand,
  ): Promise<ChangeEventStateResponse> | Observable<ChangeEventStateResponse> | ChangeEventStateResponse;

  manageRequirements(
    request: ManageRequirementCommand,
  ): Promise<ManageRequirementsResponse> | Observable<ManageRequirementsResponse> | ManageRequirementsResponse;

  deleteEvent(
    request: DeleteEventCommand,
  ): Promise<DeleteEventResponse> | Observable<DeleteEventResponse> | DeleteEventResponse;
}

export function EventCommandServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createEvent",
      "updateEvent",
      "changeEventState",
      "manageRequirements",
      "deleteEvent",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("EventCommandService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("EventCommandService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EVENT_COMMAND_SERVICE_NAME = "EventCommandService";

export interface EventQueryServiceClient {
  getEvent(request: GetEventQuery): Observable<GetEventResponse>;

  searchEvents(request: SearchEventsQuery): Observable<SearchEventsResponse>;

  listRequirements(request: ListRequirementsQuery): Observable<ListRequirementsResponse>;
}

export interface EventQueryServiceController {
  getEvent(request: GetEventQuery): Promise<GetEventResponse> | Observable<GetEventResponse> | GetEventResponse;

  searchEvents(
    request: SearchEventsQuery,
  ): Promise<SearchEventsResponse> | Observable<SearchEventsResponse> | SearchEventsResponse;

  listRequirements(
    request: ListRequirementsQuery,
  ): Promise<ListRequirementsResponse> | Observable<ListRequirementsResponse> | ListRequirementsResponse;
}

export function EventQueryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getEvent", "searchEvents", "listRequirements"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("EventQueryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("EventQueryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EVENT_QUERY_SERVICE_NAME = "EventQueryService";

export interface TagCommandServiceClient {
  createTag(request: CreateTagCommand): Observable<CreateTagResponse>;

  updateTag(request: UpdateTagCommand): Observable<UpdateTagResponse>;

  deleteTag(request: DeleteTagCommand): Observable<DeleteTagResponse>;
}

export interface TagCommandServiceController {
  createTag(request: CreateTagCommand): Promise<CreateTagResponse> | Observable<CreateTagResponse> | CreateTagResponse;

  updateTag(request: UpdateTagCommand): Promise<UpdateTagResponse> | Observable<UpdateTagResponse> | UpdateTagResponse;

  deleteTag(request: DeleteTagCommand): Promise<DeleteTagResponse> | Observable<DeleteTagResponse> | DeleteTagResponse;
}

export function TagCommandServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createTag", "updateTag", "deleteTag"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TagCommandService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TagCommandService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TAG_COMMAND_SERVICE_NAME = "TagCommandService";

export interface TagQueryServiceClient {
  getTags(request: GetTagsQuery): Observable<GetTagsResponse>;
}

export interface TagQueryServiceController {
  getTags(request: GetTagsQuery): Promise<GetTagsResponse> | Observable<GetTagsResponse> | GetTagsResponse;
}

export function TagQueryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getTags"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TagQueryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TagQueryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TAG_QUERY_SERVICE_NAME = "TagQueryService";
