import { Column, CreateDateColumn, Entity, Index, PrimaryColumn, UpdateDateColumn } from 'typeorm';
import { EntityType } from '../enums/entity-type.enum.js';
import { FileStatus } from '../enums/file-status.enum.js';
import { RejectionReason } from '../enums/rejection-reason.enum.js';
import { ScanStatus } from '../enums/scan-status.enum.js';
import { ValidationMode } from '../enums/validation-mode.enum.js';
import { bigintNumberTransformer } from './transformers/bigint-number.transformer.js';

@Entity('files')
@Index('idx_files_entity', ['entityType', 'entityId'])
@Index('idx_files_owner', ['ownerId'])
@Index('idx_files_awaiting', ['uploadExpiresAt'], {
  where: `"scan_status" = 'AWAITING_UPLOAD'`,
})
@Index('idx_files_scanning', ['confirmedAt'], { where: `"scan_status" = 'SCANNING'` })
@Index('idx_files_unused', ['confirmedAt'], { where: `"status" = 'PENDING'` })
@Index('idx_files_reserved', ['reservedAt'], { where: `"status" = 'RESERVED'` })
@Index('idx_files_orphaned', ['updatedAt'], { where: `"status" = 'ORPHANED'` })
export class FileModel {
  /** Generated by the application (`FileId.generate()`), never by the database. */
  @PrimaryColumn({ type: 'uuid' })
  id!: string;

  @Column({ name: 'owner_id', type: 'uuid' })
  ownerId!: string;

  @Column({ name: 'entity_type', type: 'varchar' })
  entityType!: EntityType;

  @Column({ name: 'entity_id', type: 'uuid', nullable: true })
  entityId!: string | null;

  @Column({ type: 'varchar', default: FileStatus.PENDING })
  status!: FileStatus;

  @Column({ name: 'scan_status', type: 'varchar', default: ScanStatus.AWAITING_UPLOAD })
  scanStatus!: ScanStatus;

  @Column({ name: 'rejection_reason', type: 'varchar', nullable: true })
  rejectionReason!: RejectionReason | null;

  @Column({ name: 'declared_mime_type', type: 'varchar' })
  declaredMimeType!: string;

  @Column({ name: 'declared_size', type: 'bigint', transformer: bigintNumberTransformer })
  declaredSize!: number;

  @Column({
    name: 'actual_size',
    type: 'bigint',
    nullable: true,
    transformer: bigintNumberTransformer,
  })
  actualSize!: number | null;

  /** Private key of the object while it is quarantined. Never exposed. */
  @Column({ name: 'quarantine_key', type: 'varchar' })
  quarantineKey!: string;

  /** Public key, set once the file is CLEAN. */
  @Column({ name: 'public_key', type: 'varchar', nullable: true })
  publicKey!: string | null;

  /** Informative counter of scan attempts. */
  @Column({ name: 'scan_attempts', type: 'int', default: 0 })
  scanAttempts!: number;

  /** Single retry scheduled by the purge job. */
  @Column({ name: 'rescan_scheduled_at', type: 'timestamptz', nullable: true })
  rescanScheduledAt!: Date | null;

  /** SYNC or ASYNC, computed at `GenerateUploadUrl` and updated on a technical switch. */
  @Column({ name: 'validation_mode', type: 'varchar' })
  validationMode!: ValidationMode;

  @Column({ name: 'upload_expires_at', type: 'timestamptz' })
  uploadExpiresAt!: Date;

  @Column({ name: 'confirmed_at', type: 'timestamptz', nullable: true })
  confirmedAt!: Date | null;

  @Column({ name: 'scanned_at', type: 'timestamptz', nullable: true })
  scannedAt!: Date | null;

  @Column({ name: 'reserved_at', type: 'timestamptz', nullable: true })
  reservedAt!: Date | null;

  @Column({ name: 'attached_at', type: 'timestamptz', nullable: true })
  attachedAt!: Date | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt!: Date;
}
