// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.13.0
//   protoc               unknown
// source: volontariapp/post/comment.command.proto

/* eslint-disable */

export interface CreateCommentCommand {
  postId: string;
  content: string;
}

export interface DeleteCommentCommand {
  id: string;
  postId: string;
}
