// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: volontariapp/post/comment.query.proto

/* eslint-disable */
import { PaginationRequest } from "../common/pagination.js";

export interface ListCommentsQuery {
  postId: string;
  pagination: PaginationRequest | undefined;
}
