// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: volontariapp/post/post.command.proto

/* eslint-disable */
import { Post } from "./post.js";

export interface CreatePostCommand {
  title: string;
  content: string;
}

export interface AdminCreatePostCommand {
  authorId: string;
  title: string;
  content: string;
}

export interface UpdatePostCommand {
  post: Post | undefined;
  updateMask: string[];
}

export interface DeletePostCommand {
  id: string;
}

export interface DeleteMyPostsCommand {
}
