// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: volontariapp/post/post.services.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { CreatePostCommand, DeletePostCommand, UpdatePostCommand } from './post.command.js';
import { ListPostsQuery, PostQuery } from './post.query.js';
import {
  CreatePostResponse,
  DeletePostResponse,
  GetPostResponse,
  ListPostsResponse,
  UpdatePostResponse,
} from './post.responses.js';

export interface PostServiceClient {
  getPost(request: PostQuery): Observable<GetPostResponse>;

  listPosts(request: ListPostsQuery): Observable<ListPostsResponse>;

  createPost(request: CreatePostCommand): Observable<CreatePostResponse>;

  updatePost(request: UpdatePostCommand): Observable<UpdatePostResponse>;

  deletePost(request: DeletePostCommand): Observable<DeletePostResponse>;
}

export interface PostServiceController {
  getPost(
    request: PostQuery,
  ): Promise<GetPostResponse> | Observable<GetPostResponse> | GetPostResponse;

  listPosts(
    request: ListPostsQuery,
  ): Promise<ListPostsResponse> | Observable<ListPostsResponse> | ListPostsResponse;

  createPost(
    request: CreatePostCommand,
  ): Promise<CreatePostResponse> | Observable<CreatePostResponse> | CreatePostResponse;

  updatePost(
    request: UpdatePostCommand,
  ): Promise<UpdatePostResponse> | Observable<UpdatePostResponse> | UpdatePostResponse;

  deletePost(
    request: DeletePostCommand,
  ): Promise<DeletePostResponse> | Observable<DeletePostResponse> | DeletePostResponse;
}

export function PostServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getPost',
      'listPosts',
      'createPost',
      'updatePost',
      'deletePost',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('PostService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('PostService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const POST_SERVICE_NAME = 'PostService';
