// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: volontariapp/post/post.services.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import {
  AdminCreatePostCommand,
  CreatePostCommand,
  DeleteMyPostsCommand,
  DeletePostCommand,
  UpdatePostCommand,
} from "./post.command.js";
import { GetPostQuery, ListPostsQuery } from "./post.query.js";
import {
  AdminCreatePostResponse,
  CreatePostResponse,
  DeleteMyPostsResponse,
  DeletePostResponse,
  GetPostResponse,
  ListPostsResponse,
  UpdatePostResponse,
} from "./post.responses.js";

export interface PostServiceClient {
  getPost(request: GetPostQuery): Observable<GetPostResponse>;

  listPosts(request: ListPostsQuery): Observable<ListPostsResponse>;

  createPost(request: CreatePostCommand): Observable<CreatePostResponse>;

  adminCreatePost(request: AdminCreatePostCommand): Observable<AdminCreatePostResponse>;

  updatePost(request: UpdatePostCommand): Observable<UpdatePostResponse>;

  deletePost(request: DeletePostCommand): Observable<DeletePostResponse>;

  deleteMyPosts(request: DeleteMyPostsCommand): Observable<DeleteMyPostsResponse>;
}

export interface PostServiceController {
  getPost(request: GetPostQuery): Promise<GetPostResponse> | Observable<GetPostResponse> | GetPostResponse;

  listPosts(request: ListPostsQuery): Promise<ListPostsResponse> | Observable<ListPostsResponse> | ListPostsResponse;

  createPost(
    request: CreatePostCommand,
  ): Promise<CreatePostResponse> | Observable<CreatePostResponse> | CreatePostResponse;

  adminCreatePost(
    request: AdminCreatePostCommand,
  ): Promise<AdminCreatePostResponse> | Observable<AdminCreatePostResponse> | AdminCreatePostResponse;

  updatePost(
    request: UpdatePostCommand,
  ): Promise<UpdatePostResponse> | Observable<UpdatePostResponse> | UpdatePostResponse;

  deletePost(
    request: DeletePostCommand,
  ): Promise<DeletePostResponse> | Observable<DeletePostResponse> | DeletePostResponse;

  deleteMyPosts(
    request: DeleteMyPostsCommand,
  ): Promise<DeleteMyPostsResponse> | Observable<DeleteMyPostsResponse> | DeleteMyPostsResponse;
}

export function PostServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getPost",
      "listPosts",
      "createPost",
      "adminCreatePost",
      "updatePost",
      "deletePost",
      "deleteMyPosts",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PostService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PostService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const POST_SERVICE_NAME = "PostService";
