// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.13.0
//   protoc               unknown
// source: volontariapp/post/post.command.proto

/* eslint-disable */
import { Post } from "./post.js";

export interface CreatePostCommand {
  title: string;
  content: string;
  eventId?:
    | string
    | undefined;
  /** Ids of the uploaded files, in display order. Empty for a post without media. */
  fileIds: string[];
  /** Client-generated key: retrying the same request yields the same post. */
  idempotencyKey: string;
}

export interface AdminCreatePostCommand {
  authorId: string;
  title: string;
  content: string;
  eventId?: string | undefined;
}

export interface UpdatePostCommand {
  post: Post | undefined;
  updateMask: string[];
}

export interface DeletePostCommand {
  id: string;
}

export interface DeleteMyPostsCommand {
}
