name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

jobs:
  run-pipeline:
    uses: Volontariapp/ci-tools/.github/workflows/npm-packages/pipeline.yml@main
    secrets:
      ORG_REPO_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
