name: Job - Version Changelogs & Publish

on:
  workflow_call:
    inputs:
      changed_packages:
        required: true
        type: string
    secrets:
      ORG_REPO_TOKEN:
        required: true
      NPM_TOKEN:
        required: true

jobs:
  release:
    name: Version Changelogs & Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.ORG_REPO_TOKEN }}
          fetch-depth: 0

      - name: Enable Corepack
        shell: bash
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.0
          cache: yarn
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn install --immutable

      - name: Unified NPM & Yarn Auth
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          yarn config set 'npmRegistries["//registry.npmjs.org/"].npmAuthToken' "${{ secrets.NPM_TOKEN }}"

      - name: Version and publish packages
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bash scripts/ci-package-publish.sh --changed-packages '${{ inputs.changed_packages }}'

      - name: Post Comment on PR
        if: github.event_name == 'pull_request' && steps.release.outputs.mode == 'snapshot' && steps.release.outputs.snapshot_tags != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAGS: ${{ steps.release.outputs.snapshot_tags }}
        run: |
          IFS=',' read -ra ADDR <<< "$TAGS"
          for i in "${ADDR[@]}"; do
            PKG=$(echo "$i" | sed 's/@[^@]*$//')
            gh pr comment ${{ github.event.pull_request.number }} --body "🚀 Nouvelle version de \`$PKG\` :

            \`\`\`bash
            yarn add $i
            \`\`\`"
          done
